"""add: user foreign key at todo table

Revision ID: 561d3ab3fc47
Revises: fab076befda3
Create Date: 2022-12-18 10:53:26.007982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561d3ab3fc47'
down_revision = 'fab076befda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
