"""fix: password length

Revision ID: 746e1ce34344
Revises: eaf5bf5b08e3
Create Date: 2022-12-17 17:50:40.868970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746e1ce34344'
down_revision = 'eaf5bf5b08e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
