"""hide: password

Revision ID: 8fa80a9319ff
Revises: 746e1ce34344
Create Date: 2022-12-17 17:56:27.991802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fa80a9319ff'
down_revision = '746e1ce34344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
