"""create: todos table

Revision ID: 9b0e762a445d
Revises: 2c6c0ff902e9
Create Date: 2025-05-20 11:26:13.493019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0e762a445d'
down_revision = '2c6c0ff902e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
