"""add: login log table attribute

Revision ID: be8253631ffc
Revises: 561d3ab3fc47
Create Date: 2022-12-21 11:24:13.250165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8253631ffc'
down_revision = '561d3ab3fc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('log_info', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'log_info')
    # ### end Alembic commands ###
